version: '3.4'

services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-12345678}
      - POSTGRES_DB=${POSTGRES_DB:-taschengeldboerse}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    labels:
      traefik.basic.frontend.rule: "HostRegexp:{subdomain:[a-zA-Z0-9]+}.taschengeldboerse.io,www.taschengeldboerse.io,taschengeldboerse.io"
      traefik.basic.frontend.priority: "1"
      traefik.basic.port: "80"

  traefik:
    image: traefik:1.7.1
    command: --docker --api
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    container_name: traefik
    environment:
      DNSIMPLE_OAUTH_TOKEN: ${DNSIMPLE_OAUTH_TOKEN}
      DNSIMPLE_BASE_URL: ${DNSIMPLE_BASE_URL}
      logLevel: "DEBUG"
    labels:
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.taschengeldboerse.io"
      traefik.frontend.priority: "2"
      traefik.port: "8080"


volumes:
  postgres-data:

networks:
  web:
    external: true