version: '3.4'

services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-12345678}
      - POSTGRES_DB=${POSTGRES_DB:-taschengeldboerse}
    networks:
      - overlay
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    restart: always
    build: .
    command: python -m severus
    links:
      - postgres
    networks:
      - web
      - overlay
    labels:
      traefik.basic.frontend.rule: "Host:api.taschengeldboerse.io"
      traefik.basic.frontend.priority: "1"
      traefik.basic.port: "5000"
      traefik.docker.network: web

  web-app:
    build: ./react
    networks:
      - web
    labels:
      traefik.frontend.rule: "Host:www.taschengeldboerse.io,taschengeldboerse.io"
      traefik.mangeno.frontend.priority: "2"
      traefik.mangeno.port: "8043"
      traefik.docker.network: web

  traefik:
    image: traefik:1.7.0-rc4
    command: --docker --api
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    container_name: traefik
    environment:
      DNSIMPLE_OAUTH_TOKEN: ${DNSIMPLE_OAUTH_TOKEN}
      DNSIMPLE_BASE_URL: ${DNSIMPLE_BASE_URL}
      logLevel: "DEBUG"
    labels:
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.taschengeldboerse.io"
      traefik.frontend.priority: "2"
      traefik.port: "8080"


volumes:
  postgres-data:

networks:
  overlay:
  web:
    external: true