version: '3.4'

services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-12345678}
      - POSTGRES_DB=${POSTGRES_DB:-taschengeldboerse}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: python -m severus

volumes:
  postgres-data:
